'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("McpServiceNetFx.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 Visual Studio MCP Server 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property AppTitle() As String
            Get
                Return ResourceManager.GetString("AppTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Allow All 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonAllowAll() As String
            Get
                Return ResourceManager.GetString("ButtonAllowAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ask All 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonAskAll() As String
            Get
                Return ResourceManager.GetString("ButtonAskAll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Clear Logs 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonClearLogs() As String
            Get
                Return ResourceManager.GetString("ButtonClearLogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Close 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonClose() As String
            Get
                Return ResourceManager.GetString("ButtonClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export Logs 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonExportLogs() As String
            Get
                Return ResourceManager.GetString("ButtonExportLogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonNo() As String
            Get
                Return ResourceManager.GetString("ButtonNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 OK 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonOK() As String
            Get
                Return ResourceManager.GetString("ButtonOK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Refresh 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonRefresh() As String
            Get
                Return ResourceManager.GetString("ButtonRefresh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Reload 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonReload() As String
            Get
                Return ResourceManager.GetString("ButtonReload", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save Config 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonSaveConfig() As String
            Get
                Return ResourceManager.GetString("ButtonSaveConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start Service 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonStartService() As String
            Get
                Return ResourceManager.GetString("ButtonStartService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Stop Service 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonStopService() As String
            Get
                Return ResourceManager.GetString("ButtonStopService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Yes 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property ButtonYes() As String
            Get
                Return ResourceManager.GetString("ButtonYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Message 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property CustomMessageBoxTitle() As String
            Get
                Return ResourceManager.GetString("CustomMessageBoxTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No file 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property FileNoFile() As String
            Get
                Return ResourceManager.GetString("FileNoFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 XML Files (*.xml)|*.xml|All Files (*.*)|*.* 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property FilterXmlFiles() As String
            Get
                Return ResourceManager.GetString("FilterXmlFiles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service Settings 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property GroupServiceSettings() As String
            Get
                Return ResourceManager.GetString("GroupServiceSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Description 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderDescription() As String
            Get
                Return ResourceManager.GetString("HeaderDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Details 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderDetails() As String
            Get
                Return ResourceManager.GetString("HeaderDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Feature Name 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderFeatureName() As String
            Get
                Return ResourceManager.GetString("HeaderFeatureName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Operation 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderOperation() As String
            Get
                Return ResourceManager.GetString("HeaderOperation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderPermission() As String
            Get
                Return ResourceManager.GetString("HeaderPermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Process ID 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderProcessId() As String
            Get
                Return ResourceManager.GetString("HeaderProcessId", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Result 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderResult() As String
            Get
                Return ResourceManager.GetString("HeaderResult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Solution Path 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderSolutionPath() As String
            Get
                Return ResourceManager.GetString("HeaderSolutionPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Time 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderTime() As String
            Get
                Return ResourceManager.GetString("HeaderTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Version 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderVersion() As String
            Get
                Return ResourceManager.GetString("HeaderVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Window Caption 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property HeaderWindowCaption() As String
            Get
                Return ResourceManager.GetString("HeaderWindowCaption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Client Config: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LabelClientConfig() As String
            Get
                Return ResourceManager.GetString("LabelClientConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Instance: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LabelInstance() As String
            Get
                Return ResourceManager.GetString("LabelInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Port: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LabelPort() As String
            Get
                Return ResourceManager.GetString("LabelPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Status: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LabelStatus() As String
            Get
                Return ResourceManager.GetString("LabelStatus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Document path: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogActiveDocPath() As String
            Get
                Return ResourceManager.GetString("LogActiveDocPath", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Added {0} new tool permission items 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogAddedNewToolPermissions() As String
            Get
                Return ResourceManager.GetString("LogAddedNewToolPermissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Allowed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogAllowed() As String
            Get
                Return ResourceManager.GetString("LogAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Ask User 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogAskUser() As String
            Get
                Return ResourceManager.GetString("LogAskUser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 All permissions have been set to: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogBatchSetCompleted() As String
            Get
                Return ResourceManager.GetString("LogBatchSetCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Build Project 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogBuildProject() As String
            Get
                Return ResourceManager.GetString("LogBuildProject", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Build Solution 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogBuildSolution() As String
            Get
                Return ResourceManager.GetString("LogBuildSolution", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Start building 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogBuildStart() As String
            Get
                Return ResourceManager.GetString("LogBuildStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Completed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogCompleted() As String
            Get
                Return ResourceManager.GetString("LogCompleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data context created successfully 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogDataContextCreated() As String
            Get
                Return ResourceManager.GetString("LogDataContextCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Data context creation failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogDataContextCreateFailed() As String
            Get
                Return ResourceManager.GetString("LogDataContextCreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Denied 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogDenied() As String
            Get
                Return ResourceManager.GetString("LogDenied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Errors: {0}, Warnings: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogErrorListCounts() As String
            Get
                Return ResourceManager.GetString("LogErrorListCounts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exception 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogException() As String
            Get
                Return ResourceManager.GetString("LogException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Execution Exception 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogExecutionException() As String
            Get
                Return ResourceManager.GetString("LogExecutionException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFailed() As String
            Get
                Return ResourceManager.GetString("LogFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Feature: {0}, Permission: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFeaturePermission() As String
            Get
                Return ResourceManager.GetString("LogFeaturePermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Feature: {0}, Permission value: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFeaturePermissionValue() As String
            Get
                Return ResourceManager.GetString("LogFeaturePermissionValue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Found {0} open documents 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFoundOpenDocs() As String
            Get
                Return ResourceManager.GetString("LogFoundOpenDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool manager framework created, waiting for data context 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFrameworkCreated() As String
            Get
                Return ResourceManager.GetString("LogFrameworkCreated", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool manager framework creation failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogFrameworkCreateFailed() As String
            Get
                Return ResourceManager.GetString("LogFrameworkCreateFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get current active document information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetActiveDocStart() As String
            Get
                Return ResourceManager.GetString("LogGetActiveDocStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get Active Document 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetActiveDocument() As String
            Get
                Return ResourceManager.GetString("LogGetActiveDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get all open document information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetAllOpenDocsStart() As String
            Get
                Return ResourceManager.GetString("LogGetAllOpenDocsStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get All Open Documents 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetAllOpenDocuments() As String
            Get
                Return ResourceManager.GetString("LogGetAllOpenDocuments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get Error List 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetErrorList() As String
            Get
                Return ResourceManager.GetString("LogGetErrorList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get error list with filter level: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetErrorListStart() As String
            Get
                Return ResourceManager.GetString("LogGetErrorListStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get permission 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetPermission() As String
            Get
                Return ResourceManager.GetString("LogGetPermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get Solution Info 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetSolutionInfo() As String
            Get
                Return ResourceManager.GetString("LogGetSolutionInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get detailed solution information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetSolutionInfoStart() As String
            Get
                Return ResourceManager.GetString("LogGetSolutionInfoStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Get Tool Manager 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogGetToolManager() As String
            Get
                Return ResourceManager.GetString("LogGetToolManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Instance: {0}, Tool count: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogInstanceAndToolCount() As String
            Get
                Return ResourceManager.GetString("LogInstanceAndToolCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Visual Studio instance selection canceled 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogInstanceCanceled() As String
            Get
                Return ResourceManager.GetString("LogInstanceCanceled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 MCP Request - {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogMcpRequest() As String
            Get
                Return ResourceManager.GetString("LogMcpRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Missing required parameter: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogMissingRequiredParameter() As String
            Get
                Return ResourceManager.GetString("LogMissingRequiredParameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No active document 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogNoActiveDoc() As String
            Get
                Return ResourceManager.GetString("LogNoActiveDoc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No open documents found 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogNoOpenDocs() As String
            Get
                Return ResourceManager.GetString("LogNoOpenDocs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No permission configuration in tool manager 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogNoPermissionConfig() As String
            Get
                Return ResourceManager.GetString("LogNoPermissionConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameters cannot be null 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogParameterCannotBeNull() As String
            Get
                Return ResourceManager.GetString("LogParameterCannotBeNull", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter conversion failed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogParameterConversionFailed() As String
            Get
                Return ResourceManager.GetString("LogParameterConversionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Parameter {0} conversion failed: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogParameterConversionFailure() As String
            Get
                Return ResourceManager.GetString("LogParameterConversionFailure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission Check 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionCheck() As String
            Get
                Return ResourceManager.GetString("LogPermissionCheck", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission check 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionCheckException() As String
            Get
                Return ResourceManager.GetString("LogPermissionCheckException", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission configuration found 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionConfigFound() As String
            Get
                Return ResourceManager.GetString("LogPermissionConfigFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission configuration not found, using default permission: Ask 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionConfigNotFound() As String
            Get
                Return ResourceManager.GetString("LogPermissionConfigNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Feature: {0}, Description: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionRequestDetails() As String
            Get
                Return ResourceManager.GetString("LogPermissionRequestDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permissions 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissions() As String
            Get
                Return ResourceManager.GetString("LogPermissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission batch set 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionSet() As String
            Get
                Return ResourceManager.GetString("LogPermissionSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission configurations loaded 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionsLoaded() As String
            Get
                Return ResourceManager.GetString("LogPermissionsLoaded", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission synchronization 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionSync() As String
            Get
                Return ResourceManager.GetString("LogPermissionSync", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission value: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogPermissionValueDetails() As String
            Get
                Return ResourceManager.GetString("LogPermissionValueDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Project: {0}, Configuration: {1} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogProjectAndConfig() As String
            Get
                Return ResourceManager.GetString("LogProjectAndConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Project count: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogProjectCount() As String
            Get
                Return ResourceManager.GetString("LogProjectCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run custom tools for project: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogRunCustomToolsStart() As String
            Get
                Return ResourceManager.GetString("LogRunCustomToolsStart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run Project Custom Tools 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogRunProjectCustomTools() As String
            Get
                Return ResourceManager.GetString("LogRunProjectCustomTools", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service Started 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogServiceStarted() As String
            Get
                Return ResourceManager.GetString("LogServiceStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Port: {0}, Instance: {1}, Tool count: {2} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogServiceStartedWithDetails() As String
            Get
                Return ResourceManager.GetString("LogServiceStartedWithDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service Stopped 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogServiceStopped() As String
            Get
                Return ResourceManager.GetString("LogServiceStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Skipped 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogSkipped() As String
            Get
                Return ResourceManager.GetString("LogSkipped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Started 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogStarted() As String
            Get
                Return ResourceManager.GetString("LogStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Success 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogSuccess() As String
            Get
                Return ResourceManager.GetString("LogSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool data context not set, cannot execute tool 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogToolDataContextNotSet() As String
            Get
                Return ResourceManager.GetString("LogToolDataContextNotSet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool execution failed: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogToolExecutionFailed() As String
            Get
                Return ResourceManager.GetString("LogToolExecutionFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool Manager 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogToolManager() As String
            Get
                Return ResourceManager.GetString("LogToolManager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Tool manager not initialized 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogToolManagerNotInitialized() As String
            Get
                Return ResourceManager.GetString("LogToolManagerNotInitialized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Unknown Permission 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogUnknownPermission() As String
            Get
                Return ResourceManager.GetString("LogUnknownPermission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Allowed 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogUserAllowed() As String
            Get
                Return ResourceManager.GetString("LogUserAllowed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Denied 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogUserDenied() As String
            Get
                Return ResourceManager.GetString("LogUserDenied", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User manually stopped 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogUserStopped() As String
            Get
                Return ResourceManager.GetString("LogUserStopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Visual Studio Exited 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogVsExited() As String
            Get
                Return ResourceManager.GetString("LogVsExited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Associated Visual Studio instance exited, service will stop automatically 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogVsInstanceServiceStop() As String
            Get
                Return ResourceManager.GetString("LogVsInstanceServiceStop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Associated Visual Studio instance is closing, service will stop automatically 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogVsInstanceServiceStopClosing() As String
            Get
                Return ResourceManager.GetString("LogVsInstanceServiceStopClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Visual Studio Shutdown 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogVsShutdown() As String
            Get
                Return ResourceManager.GetString("LogVsShutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Configuration: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property LogWithConfiguration() As String
            Get
                Return ResourceManager.GetString("LogWithConfiguration", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Message: 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MessageLabel() As String
            Get
                Return ResourceManager.GetString("MessageLabel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to clear logs: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgClearLogsFailed() As String
            Get
                Return ResourceManager.GetString("MsgClearLogsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Are you sure you want to clear all logs? This action cannot be undone. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgConfirmClearLogs() As String
            Get
                Return ResourceManager.GetString("MsgConfirmClearLogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to create tool manager data context: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgCreateToolManagerContextFailed() As String
            Get
                Return ResourceManager.GetString("MsgCreateToolManagerContextFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to export logs: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgExportLogsFailed() As String
            Get
                Return ResourceManager.GetString("MsgExportLogsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to load permission configuration: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgLoadPermissionsFailed() As String
            Get
                Return ResourceManager.GetString("MsgLoadPermissionsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logs have been cleared 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgLogsCleared() As String
            Get
                Return ResourceManager.GetString("MsgLogsCleared", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logs have been exported to: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgLogsExported() As String
            Get
                Return ResourceManager.GetString("MsgLogsExported", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No instance selected 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgNoInstanceSelected() As String
            Get
                Return ResourceManager.GetString("MsgNoInstanceSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 No logs to export 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgNoLogsToExport() As String
            Get
                Return ResourceManager.GetString("MsgNoLogsToExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Do you want to allow the following operation?{0}{0}Feature: {1}{0}Description: {2} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgPermissionRequest() As String
            Get
                Return ResourceManager.GetString("MsgPermissionRequest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to refresh Visual Studio instance list: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgRefreshVsInstancesFailed() As String
            Get
                Return ResourceManager.GetString("MsgRefreshVsInstancesFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to save permission configuration: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgSavePermissionsFailed() As String
            Get
                Return ResourceManager.GetString("MsgSavePermissionsFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission configuration saved 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgSavePermissionsSuccess() As String
            Get
                Return ResourceManager.GetString("MsgSavePermissionsSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please select a Visual Studio instance first 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgSelectVsInstance() As String
            Get
                Return ResourceManager.GetString("MsgSelectVsInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service is already running 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgServiceAlreadyRunning() As String
            Get
                Return ResourceManager.GetString("MsgServiceAlreadyRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service is not running 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgServiceNotRunning() As String
            Get
                Return ResourceManager.GetString("MsgServiceNotRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to start service: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgStartServiceFailed() As String
            Get
                Return ResourceManager.GetString("MsgStartServiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Failed to stop service: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgStopServiceFailed() As String
            Get
                Return ResourceManager.GetString("MsgStopServiceFailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The associated Visual Studio instance is closing, MCP service has been automatically stopped 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgVsInstanceClosing() As String
            Get
                Return ResourceManager.GetString("MsgVsInstanceClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The associated Visual Studio instance has exited, MCP service has been automatically stopped 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property MsgVsInstanceExited() As String
            Get
                Return ResourceManager.GetString("MsgVsInstanceExited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service Running - Port: {0} 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property StatusServiceRunning() As String
            Get
                Return ResourceManager.GetString("StatusServiceRunning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 About 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabAbout() As String
            Get
                Return ResourceManager.GetString("TabAbout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Claude CLI Config 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabClaudeConfig() As String
            Get
                Return ResourceManager.GetString("TabClaudeConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 JSON Config 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabJsonConfig() As String
            Get
                Return ResourceManager.GetString("TabJsonConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Logs 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabLogs() As String
            Get
                Return ResourceManager.GetString("TabLogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 MCP Permissions 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabMcpPermissions() As String
            Get
                Return ResourceManager.GetString("TabMcpPermissions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service Management 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TabServiceManagement() As String
            Get
                Return ResourceManager.GetString("TabServiceManagement", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 © 2025 Nukepayload2
        '''This software is distributed under Apache License 2.0, permanently free.
        '''This software is protected by Chinese and international copyright laws.
        '''Privacy Policy: This software collects your Microsoft Visual Studio project information to support basic functions, and the information is only stored locally.
        '''This software does not support remote information transmission, only local network loopback transmission. 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextAboutContent() As String
            Get
                Return ResourceManager.GetString("TextAboutContent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 About This Software 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextAboutTitle() As String
            Get
                Return ResourceManager.GetString("TextAboutTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Run this command to add MCP server to Claude Desktop 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextClaudeConfigHint() As String
            Get
                Return ResourceManager.GetString("TextClaudeConfigHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Add this configuration to your MCP client configuration file 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextJsonConfigHint() As String
            Get
                Return ResourceManager.GetString("TextJsonConfigHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Please select an instance from the list above 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextSelectInstance() As String
            Get
                Return ResourceManager.GetString("TextSelectInstance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Service not started 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TextServiceNotStarted() As String
            Get
                Return ResourceManager.GetString("TextServiceNotStarted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Confirm 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleConfirm() As String
            Get
                Return ResourceManager.GetString("TitleConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Confirm Clear 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleConfirmClear() As String
            Get
                Return ResourceManager.GetString("TitleConfirmClear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Error 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleError() As String
            Get
                Return ResourceManager.GetString("TitleError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export Logs 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleExportLogs() As String
            Get
                Return ResourceManager.GetString("TitleExportLogs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Export Successful 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleExportSuccess() As String
            Get
                Return ResourceManager.GetString("TitleExportSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Hint 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleHint() As String
            Get
                Return ResourceManager.GetString("TitleHint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Information 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleInfo() As String
            Get
                Return ResourceManager.GetString("TitleInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Instance Closing 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleInstanceClosing() As String
            Get
                Return ResourceManager.GetString("TitleInstanceClosing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Instance Exited 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleInstanceExited() As String
            Get
                Return ResourceManager.GetString("TitleInstanceExited", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Operation Successful 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleOperationSuccess() As String
            Get
                Return ResourceManager.GetString("TitleOperationSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Permission Confirmation 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitlePermissionConfirm() As String
            Get
                Return ResourceManager.GetString("TitlePermissionConfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Save Successful 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleSaveSuccess() As String
            Get
                Return ResourceManager.GetString("TitleSaveSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Warning 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property TitleWarning() As String
            Get
                Return ResourceManager.GetString("TitleWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 User Message 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property UserMessageTitle() As String
            Get
                Return ResourceManager.GetString("UserMessageTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
